### ISSUE TITLE
Meaning Icon

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi#912]
Let's open this issue to discuss the meaning icon

**Comment by Phillipus** [comment]
I can discuss the meaning of life...

**Comment by jbsarrodie** [comment]
>I can discuss the meaning of life...

 ;-)

I've just pushed a proposal for an enhanced Meaning icon. It is based on bezier curves. I've configured it so that points and control points are on a 12x7 grid (easier to manage). You can do simulations using [this online tool](https://www.victoriakirst.com/beziertool/) and setting [this background image](https://media.istockphoto.com/id/838296134/fr/vectoriel/cahier-quadrill%C3%A9-papier-vecteur-sans-couture-patron.jpg?s=612x612&w=0&k=20&c=x1cGez-dVkyD_OBExws8vA1FG36jcbIZtSkShbT9oHE=).

Here's what I used while coding:
![image](https://user-images.githubusercontent.com/5757396/220136656-6dc9f81e-b053-4072-856a-5299ff7be7c3.png)

**Comment by Phillipus** [comment]
Beautiful. :-)

But you missed an important change:

Remove this comment:

```// The following is the most awful code to draw a cloud...```

and replace with something appropriate. ;-)

**Comment by Phillipus** [comment]
The path code is duplicated could it be used just once?

**Comment by jbsarrodie** [comment]
> The path code is duplicated could it be used just once?

If everything else is ok, then, yes, I can refactor it (and add a helper function to simplify the calls to `.cubicTo()`)

**Comment by Phillipus** [comment]
> If everything else is ok

Superb work! 👏 

> I can refactor it 

Please do. Do a force push if you can. :-)

**Comment by jbsarrodie** [comment]
> Please do. Do a force push if you can. :-)

Done ;-)

**Comment by Phillipus** [comment]
Merged to master, thank-you. :-)
